title: Alleluia Rehuellah Alefika Ndolu
# logo: /assets/img/headshot_circle.png
#description: Alleluia is an IT student with a strong interest in data science and artificial intelligence (AI). Experienced in analyzing complex data and applying the latest analytical techniques and AI algorithms, I have a deep understanding of programming, machine learning, and statistics. With strong collaboration skills, I have experience working in teams to achieve common goals.
#show_downloads: true
theme: jekyll-theme-minimal
